version: "3.9"
services:
  mongo:
    image: mongo:6
    restart: always
    ports: ["27017:27017"]
    volumes: [ "mongo_data:/data/db" ]
  api:
    build: ./backend
    env_file: ./backend/.env
    ports: ["8080:8080"]
    volumes: [ "./backend/uploads:/usr/src/app/uploads" ]
    depends_on: [ mongo ]
  web:
    build: ./frontend
    environment:
      - VITE_API_BASE=http://localhost:8080
    ports: ["5173:80"]
    depends_on: [ api ]
volumes:
  mongo_data: